### ISSUE TITLE
omp.h not found

### ISSUE THREAD

**Issue by tcovert** [julianhinz/R_glmhdfe#1] opened 2019-03-23 02:09 UTC
Excited to try this package!  However, I can't get it installed:
```
> remotes::install_github("julianhinz/R_glmhdfe")
Downloading GitHub repo julianhinz/R_glmhdfe@master
   checking for file ‘/private/var/folders/j0/z3qxz_r91wjgp5rdgwm0fnp043wfzq/T/R✔  checking for file ‘/private/var/folders/j0/z3qxz_r91wjgp5rdgwm0fnp043wfzq/T/RtmprvR7gg/remotes3387710a2cd0/julianhinz-R_glmhdfe-1296748/DESCRIPTION’
─  preparing ‘glmhdfe’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘glmhdfe_0.4.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘glmhdfe’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c irls_foc.cpp -o irls_foc.o
irls_foc.cpp:2:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [irls_foc.o] Error 1
ERROR: compilation failed for package ‘glmhdfe’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/glmhdfe’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/j0/z3qxz_r91wjgp5rdgwm0fnp043wfzq/T//RtmprvR7gg/file33875d5931e/glmhdfe_0.4.tar.gz’ had non-zero exit status
```

This is *after* updating Rcpp, RcppArmadillo, etc.  Any suggestions for how to make this work?  For the record, I am using R 3.5.1 on a macOS machine.  Might this have something to do with item 2.10.3 here?  https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf

**Comment by julianhinz** [comment] 2019-03-23 18:19
Great catch. While I can't reproduce the problem, there's no need for `omp` (yet) anyway. Should be fixed now. Can you confirm it works after reinstalling?

**Comment by tcovert** [comment] 2019-03-23 18:35
worked!  I'm gonna post another minor annoyance (not strictly speaking a bug) in another issue

**Comment by julianhinz** [comment] 2019-03-24 11:15
Great!

**Closed as completed by julianhinz** 2019-03-24 11:15 UTC
